# Generated by Django 5.2.4 on 2025-07-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourpackage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='package_images/'),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tourpackage',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
