# Generated by Django 5.2.4 on 2025-07-16 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_tourpackage_image_alter_tourpackage_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tourpackage')),
            ],
        ),
    ]
